language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y --no-install-recommends asciidoc docbook-xml xsltproc libxml2-utils
script: autoreconf -i && ./configure && make check
